# Generated by Django 6.0.4 on 2026-06-17 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('media', models.FileField(upload_to='ads/', verbose_name='فيديو أو صورة')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخدمة')),
                ('prefix', models.CharField(max_length=2, verbose_name='حرف التذكرة (مثل A)')),
                ('avg_service_time', models.PositiveIntegerField(default=5, verbose_name='متوسط وقت الخدمة (دقائق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Q-System', max_length=100, verbose_name='اسم النظام')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='اللوجو')),
                ('primary_color', models.CharField(default='#2C3E50', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#D35400', max_length=7, verbose_name='اللون الثانوي')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='صورة الخلفية')),
                ('announcement_text', models.TextField(blank=True, max_length=1000, verbose_name='نص الشريط (استخدم [time] للوقت و [date] للتاريخ)')),
                ('enable_voice_alert', models.BooleanField(default=True, verbose_name='تفعيل التنبيه الصوتي')),
                ('last_reset_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم الشباك')),
                ('is_active', models.BooleanField(default=True, verbose_name='يعمل حالياً')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('services', models.ManyToManyField(related_name='counters', to='QSapp1.service', verbose_name='الخدمات التي يقدمها')),
            ],
            options={
                'verbose_name': 'شباك',
                'verbose_name_plural': 'الشبابيك',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم التذكرة')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('calling', 'جاري النداء'), ('serving', 'قيد الخدمة'), ('completed', 'مكتملة'), ('skipped', 'تم التخطي')], default='waiting', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت قطع التذكرة')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النداء')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء الخدمة')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QSapp1.counter', verbose_name='الشباك المستدعي')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QSapp1.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'تذكرة',
                'verbose_name_plural': 'التذاكر',
                'ordering': ['created_at'],
            },
        ),
    ]
